version: "2"

services:
  jenkins:
    image: 'jenkins/jenkins:lts'
    container_name: 'jenkins'
    environment:
        JAVA_OPTS: "-Djava.awt.headless=true"
        NEXUS_URL: "http://nexus3:8081"
    ports:
      - '8080:8080'
      - "50000:50000"
    volumes:
      - 'jenkins_data:/var/jenkins_home'
  nexus:
    image: sonatype/nexus:oss
    container_name: 'nexus'
    volumes:
      - "nexus-data:/sonatype-work"
    ports:
      - "8081:8081"
  nexus3:
    image: sonatype/nexus3
    container_name: 'nexus3'
    volumes:
      - "nexus3-data:/sonatype-work"
    ports:
      - "8082:8081"

volumes:
  nexus-data: {}
  nexus3-data: {}
  jenkins_data:
    driver: local